import type { BusinessInfo, CenterInfo, ContactInfo } from "@/types/dashboard"

export const DEFAULT_BUSINESS: BusinessInfo = {
  name: "Zscaler Inc.",
  incYear: "2007",
  revenue: "$2167 Mn",
  employees: "7384",
  headquarters: "California, United States",
  industry: "Security and Compliance Software",
  companyType: "Public",
  services: [
    "Cyber threat Protection",
    "Data Protection",
    "Digital Experience Management",
    "Security Strategy",
  ],
  about: "Zscaler, Inc. is a cloud-based information security company that provides internet security, web filtering, and secure access solutions for businesses and organizations. Their platform enables secure and fast connections between users and applications, regardless of device, location, or network.",
  socialLinks: {
    website: "https://zscaler.com",
    linkedin: "https://linkedin.com/company/zscaler",
    twitter: "https://x.com/zscaler",
    instagram: "https://instagram.com/zscaler",
  },
  stockTicker: "ZS",
  financials: {
    revenue: "$2,167 Mn",
    netIncome: "$430 Mn",
    marketCap: "$31.2 Bn",
    stockPrice: "$213.45",
  },
  executives: [
    { name: "Jay Chaudhry", title: "Chairman & CEO", since: "2007" },
    { name: "Remo Canessa", title: "Chief Financial Officer", since: "2012" },
    { name: "Robert Schlossman", title: "Chief Legal Officer", since: "2020" },
    { name: "Dali Rajic", title: "Chief Revenue Officer", since: "2022" },
    { name: "Deepen Desai", title: "Chief Security Officer", since: "2021" },
  ],
  competitors: [
    { name: "Palo Alto Networks", industry: "Cybersecurity", marketCap: "$120.5 Bn" },
    { name: "CrowdStrike", industry: "Endpoint Security", marketCap: "$74.2 Bn" },
    { name: "Fortinet", industry: "Network Security", marketCap: "$58.9 Bn" },
    { name: "Cloudflare", industry: "Web Security", marketCap: "$35.1 Bn" },
    { name: "Check Point Software", industry: "Cybersecurity", marketCap: "$18.7 Bn" },
  ],
}

export const DEFAULT_CENTERS: CenterInfo[] = [
  {
    legalName: "Zscaler Softech India Pvt. Ltd.",
    incYear: "2007",
    centerType: "IT",
    location: "Bengaluru",
    employeeCount: "1001",
    focusRegions: ["Global", "APAC", "ASEAN", "Japan"],
    services: {
      "IT Services": [
        "Web Security Service",
        "Data Protection Services",
        "Cloud Security Services",
        "Web Managing Services",
        "Global IT Service Desk Management",
      ],
    },
    techStack: ["AWS Lambda", "Terraform", "Microsoft Azure", "Salesforce Sales Cloud"],
    address: "Bengaluru, Karnataka, India",
    phone: null,
    accountName: "Zscaler Inc.",
  },
  {
    legalName: "Zscaler Softech India Pvt. Ltd.",
    incYear: "2024",
    centerType: "IT",
    location: "Hyderabad",
    employeeCount: "113",
    focusRegions: ["Global", "India"],
    services: {
      "IT Services": [
        "Platform Engineering",
        "IT Infrastructure",
        "Cloud Services",
        "IT Architecture",
        "Artificial Intelligence",
        "Machine Learning",
        "Data Center Operations",
      ],
    },
    techStack: ["Microsoft Azure", "Terraform", "Kubernetes", "AWS Cloud", "Ansible"],
    address: "Hyderabad, Telangana, India",
    phone: null,
    accountName: "Zscaler Inc.",
  },
  {
    legalName: "Alcon Laboratories India Pvt. Ltd.",
    incYear: "2018",
    centerType: "GBS",
    location: "Bengaluru",
    employeeCount: "1001",
    focusRegions: ["Global", "APAC", "EMEA"],
    services: {
      "IT Services": ["IT support", "IT Security Services", "Cybersecurity", "Cyber Threat Intelligence"],
      "ER&D": ["R&D Service", "Development of Materials"],
      FnA: [
        "Financial Planning & Analysis",
        "P&L Management",
        "Financial Reporting",
        "Budgeting & Forecasting",
        "Variance Analysis",
        "Treasury Management",
      ],
      HR: ["Talent Acquisition", "Employee Relations"],
      "Procurement and Supply Chain": [
        "Supply Chain Analytics",
        "Spend Analysis",
        "Supplier Performance",
        "Global Procurement Operations",
        "Contract Management",
        "Strategic Sourcing",
        "Supplier Evaluation",
        "Supplier Negotiation",
      ],
      "Sales & Marketing": ["Sales & Marketing Operations"],
      "Customer Support Services": ["Quality Assurance", "Customer Service", "Customer Experience"],
      "Others Service": ["Government Affairs Management"],
    },
    techStack: [
      "SAP ERP",
      "SAP Ariba",
      "SAP MM",
      "Coupa Supplier Portal",
      "ServiceNow Procurement Service Management",
      "Workday HCM",
      "SAP FICO",
    ],
    address: "11th Floor, RMZ Azure, Bellary Road, Hebbal, Bengaluru - 560092, Karnataka",
    phone: "8045444444",
    accountName: "Alcon Inc.",
  },
]

export const DEFAULT_CONTACTS: ContactInfo[] = [
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Vishal",
    lastName: "Gautam",
    designation: "Vice President, Engineering & Site Managing Director",
    email: "vgautam@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/gautamvishal",
    career: [
      "Former Head of APAC Payments & Head of Global Verification and Compliance at Stripe",
      "Former Senior Engineering Leader at Amazon",
      "Former Software Development Manager III at Amazon",
      "Former Manager Technology at SapientNitro",
      "Former Project Lead at UnitedHealthcare",
    ],
    currentProfile: [
      "Currently serving as VP of Engineering & Site Managing Director at Zscaler India, responsible for scaling the India Development Center.",
      "In this role, he leads engineering strategy and execution for cloud security initiatives, while driving growth and operational excellence in Zscaler's India tech hub.",
    ],
    qualifications: [
      "B.Tech in Computer Science from Gurukula Kangri Vishwavidyalaya (2000-2004)",
      "I.Sc. in Physics, Chemistry, Mathematics from Science College, Patna (1997-1999)",
      "10th grade with PCM from Don Bosco Academy, Patna (1997)",
    ],
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Kirabkumar",
    lastName: "D G",
    designation: "Director of Engineering",
    email: "kirankumardg@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/kirankumardg",
    career: [
      "Former Senior Engineering Manager at Cisco Systems",
      "Former Technical Lead at Juniper Networks",
      "Former Software Engineer at Wipro Technologies",
    ],
    currentProfile: [
      "Currently serving as Director of Engineering at Zscaler, leading a team focused on Zero Trust Exchange platform development.",
      "Drives architecture decisions for cloud-native security solutions and oversees cross-functional engineering delivery across multiple product lines.",
    ],
    qualifications: [
      "M.Tech in Computer Science & Engineering from IIT Bombay (2008-2010)",
      "B.E. in Information Science from RVCE, Bengaluru (2003-2007)",
    ],
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Saurav",
    lastName: "G",
    designation: "Director of Engineering",
    email: "sauravg@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/sauravmware",
    career: [
      "Former Senior Engineering Manager at VMware",
      "Former Staff Engineer at VMware",
      "Former Technical Lead at Oracle",
      "Former Software Developer at Infosys",
    ],
    currentProfile: [
      "Currently serving as Director of Engineering at Zscaler, overseeing the Data Protection engineering team.",
      "Responsible for building scalable DLP and CASB solutions, driving innovation in cloud data security, and managing a team of 50+ engineers across multiple product verticals.",
    ],
    qualifications: [
      "M.S. in Computer Science from University of Texas at Dallas (2010-2012)",
      "B.Tech in Electronics & Communication from NIT Warangal (2004-2008)",
    ],
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Kishore",
    lastName: "Thakur",
    designation: "Senior Director, Site Reliability Engineering",
    email: "kthakur@zscaler.com",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    linkedin: "linkedin.com/in/kishorethakur",
    career: [
      "Former Head of SRE at Nutanix",
      "Former Principal SRE Manager at Microsoft Azure",
      "Former Senior DevOps Lead at Salesforce",
      "Former Systems Architect at Yahoo!",
    ],
    currentProfile: [
      "Currently serving as Senior Director of Site Reliability Engineering at Zscaler, leading the Hyderabad SRE center.",
      "Oversees platform reliability, incident management, and infrastructure automation for Zscaler's global cloud security platform processing 400B+ daily transactions.",
    ],
    qualifications: [
      "M.Tech in Distributed Systems from IIIT Hyderabad (2006-2008)",
      "B.Tech in Computer Science from JNTU Hyderabad (2001-2005)",
    ],
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Satish",
    lastName: "Sreenivasaiah",
    designation: "Director - Product Security Engineering",
    email: "satishsreenivasaiah@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/satish-sreenivasaiah-b661983/",
    career: [
      "Former Security Engineering Manager at Palo Alto Networks",
      "Former Senior Security Engineer at Symantec",
      "Former Application Security Lead at Flipkart",
      "Former Security Analyst at TCS",
    ],
    currentProfile: [
      "Currently serving as Director of Product Security Engineering at Zscaler, leading security assurance for the entire product portfolio.",
      "Responsible for application security, vulnerability management, penetration testing, and secure SDLC practices across all engineering teams.",
    ],
    qualifications: [
      "M.S. in Information Security from Carnegie Mellon University (2011-2013)",
      "B.E. in Computer Science from BMS College of Engineering, Bengaluru (2005-2009)",
      "CISSP, OSCP, CEH Certified",
    ],
  },
]
