import type { BusinessInfo, CenterInfo, ContactInfo } from "@/types/dashboard"

export const DEFAULT_BUSINESS: BusinessInfo = {
  name: "Zscaler Inc.",
  incYear: "2007",
  revenue: "$2167 Mn",
  employees: "7384",
  headquarters: "California, United States",
  industry: "Security and Compliance Software",
  companyType: "Public",
  services: [
    "Cyber threat Protection",
    "Data Protection",
    "Digital Experience Management",
    "Security Strategy",
  ],
  about: "Zscaler, Inc. is a cloud-based information security company that provides internet security, web filtering, and secure access solutions for businesses and organizations. Their platform enables secure and fast connections between users and applications, regardless of device, location, or network.",
  socialLinks: {
    website: "https://zscaler.com",
    linkedin: "https://linkedin.com/company/zscaler",
    twitter: "https://x.com/zscaler",
    instagram: "https://instagram.com/zscaler",
  },
}

export const DEFAULT_CENTERS: CenterInfo[] = [
  {
    legalName: "Zscaler Softech India Pvt. Ltd.",
    incYear: "2007",
    centerType: "IT",
    location: "Bengaluru",
    employeeCount: "1001",
    focusRegions: ["Global", "APAC", "ASEAN", "Japan"],
    services: {
      "IT Services": [
        "Web Security Service",
        "Data Protection Services",
        "Cloud Security Services",
        "Web Managing Services",
        "Global IT Service Desk Management",
      ],
    },
    techStack: ["AWS Lambda", "Terraform", "Microsoft Azure", "Salesforce Sales Cloud"],
    address: "Bengaluru, Karnataka, India",
    phone: null,
    accountName: "Zscaler Inc.",
  },
  {
    legalName: "Zscaler Softech India Pvt. Ltd.",
    incYear: "2024",
    centerType: "IT",
    location: "Hyderabad",
    employeeCount: "113",
    focusRegions: ["Global", "India"],
    services: {
      "IT Services": [
        "Platform Engineering",
        "IT Infrastructure",
        "Cloud Services",
        "IT Architecture",
        "Artificial Intelligence",
        "Machine Learning",
        "Data Center Operations",
      ],
    },
    techStack: ["Microsoft Azure", "Terraform", "Kubernetes", "AWS Cloud", "Ansible"],
    address: "Hyderabad, Telangana, India",
    phone: null,
    accountName: "Zscaler Inc.",
  },
  {
    legalName: "Alcon Laboratories India Pvt. Ltd.",
    incYear: "2018",
    centerType: "GBS",
    location: "Bengaluru",
    employeeCount: "1001",
    focusRegions: ["Global", "APAC", "EMEA"],
    services: {
      "IT Services": ["IT support", "IT Security Services", "Cybersecurity", "Cyber Threat Intelligence"],
      "ER&D": ["R&D Service", "Development of Materials"],
      FnA: [
        "Financial Planning & Analysis",
        "P&L Management",
        "Financial Reporting",
        "Budgeting & Forecasting",
        "Variance Analysis",
        "Treasury Management",
      ],
      HR: ["Talent Acquisition", "Employee Relations"],
      "Procurement and Supply Chain": [
        "Supply Chain Analytics",
        "Spend Analysis",
        "Supplier Performance",
        "Global Procurement Operations",
        "Contract Management",
        "Strategic Sourcing",
        "Supplier Evaluation",
        "Supplier Negotiation",
      ],
      "Sales & Marketing": ["Sales & Marketing Operations"],
      "Customer Support Services": ["Quality Assurance", "Customer Service", "Customer Experience"],
      "Others Service": ["Government Affairs Management"],
    },
    techStack: [
      "SAP ERP",
      "SAP Ariba",
      "SAP MM",
      "Coupa Supplier Portal",
      "ServiceNow Procurement Service Management",
      "Workday HCM",
      "SAP FICO",
    ],
    address: "11th Floor, RMZ Azure, Bellary Road, Hebbal, Bengaluru - 560092, Karnataka",
    phone: "8045444444",
    accountName: "Alcon Inc.",
  },
]

export const DEFAULT_CONTACTS: ContactInfo[] = [
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Vishal",
    lastName: "Gautam",
    designation: "Vice President, Engineering & Site Managing Director",
    email: "vgautam@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/gautamvishal",
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Kirabkumar",
    lastName: "D G",
    designation: "Director of Engineering",
    email: "kirankumardg@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/kirankumardg",
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Saurav",
    lastName: "G",
    designation: "Director of Engineering",
    email: "sauravg@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/sauravmware",
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Kishore",
    lastName: "Thakur",
    designation: "Senior Director, Site Reliability Engineering",
    email: "kthakur@zscaler.com",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    linkedin: "linkedin.com/in/kishorethakur",
  },
  {
    accountName: "Zscaler Inc.",
    entityName: "Zscaler Softech India Pvt. Ltd.",
    firstName: "Satish",
    lastName: "Sreenivasaiah",
    designation: "Director - Product Security Engineering",
    email: "satishsreenivasaiah@zscaler.com",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    linkedin: "linkedin.com/in/satish-sreenivasaiah-b661983/",
  },
]
